# docker build -t py35-songlist .

postgres:
    image: postgres:9.5
    restart: always
    log_opt:
        max-size: 5m
    container_name: songlist-postgres
    # net: host
    ports:
        - 5433:5432
    volumes:
        - ./pgdata:/pgdata
    environment:
        - PGDATA=/pgdata
        - POSTGRES_DB=songbook

gunicorn:
    image: py35-songlist
    restart: always
    log_opt:
        max-size: 5m
    container_name: songlist-gunicorn
    net: host
    volumes:
        - .:/app
    working_dir: /app
    command: gunicorn songbook.wsgi:application --workers 1 --bind=unix:/app/common/gunicorn.sock

nginx:
    image: nginx
    restart: always
    log_opt:
        max-size: 5m
    container_name: songlist-nginx
    net: host
    volumes:
        - .:/app
        - ./common/nginx.conf:/etc/nginx/nginx.conf:ro
