gunicorn:
    image: py35
    restart: always
    log_opt:
        max-size: 5m
    container_name: gunicorn
    net: host
    volumes:
        - .:/app
    working_dir: /app
    command: gunicorn songbook.wsgi:application --workers 1 --bind=unix:/app/common/gunicorn.sock

nginx:
    image: nginx
    restart: always
    log_opt:
        max-size: 5m
    container_name: nginx
    net: host
    volumes:
        - .:/app
        - ./common/nginx.conf:/etc/nginx/nginx.conf:ro
